### ISSUE TITLE
ppf src path always resolves to .\build\classes\main

### ISSUE THREAD

**Issue by riv3n** [AppSecDev/appscan-source-gradle-plugin#14]
My ppf always resolves the src path to .\build\classes\main. Is there a way to specify this?

**Comment by hmozaffari** [comment]
Plugin assumes code is already compiled and relies on byte codes instead of source code. That's why it refers to ./build/classes.
I needed same option and added that option in my forked repository:
[https://github.com/hmozaffari/appscan-source-gradle-plugin](https://github.com/hmozaffari/appscan-source-gradle-plugin)

**Comment by mattmurp** [comment]
I commented on the pull request and will merge it in once that minor point is addressed.

**Comment by hmozaffari** [comment]
Done :)

**Comment by mattmurp** [comment]
Sorry for the delay.  This has been merged.
